import { SubscriptionFeatureKey } from '@/types/subscription';

export const SUBSCRIPTION_FEATURE_LABELS: Record<
  SubscriptionFeatureKey,
  string
> = {
  emailNotifications: 'Email notifications',
  whatsAppNotifications: 'WhatsApp notifications',
  manualAttendance: 'Manual attendance',
  liveAttendance: 'Live attendance',
  doorAccessAttendance: 'Door access attendance',
  devicesPerUserLimit: 'Devices per user',
  staffLoginLimit: 'Staff login limit',
  trainerLoginLimit: 'Trainer login limit',
  memberManagement: 'Member management',
  trainerManagement: 'Trainer management',
  staffManagement: 'Staff management',
  membershipManagement: 'Membership management',
  paymentTracking: 'Payment tracking',
  memberPortal: 'Member portal',
  qrCodeCheckIn: 'QR code check-in',
  basicDashboard: 'Basic dashboard',
  invoiceGeneration: 'Invoice generation',
  expenseTracker: 'Expense tracker',
  leadManagement: 'Lead management',
  attendanceTracking: 'Attendance tracking',
  offersDiscounts: 'Offers and discounts',
  roleBasedAccess: 'Role-based access',
  trainerPortal: 'Trainer portal',
  ptCollections: 'PT collections',
  commissionTracking: 'Commission tracking',
  basicReports: 'Basic reports',
  revenueAnalytics: 'Revenue analytics',
  advancedAnalytics: 'Advanced analytics',
  exportToExcel: 'Export to Excel',
  customReports: 'Custom reports',
  emailSupport: 'Email support',
  chatSupport: 'Chat support',
  phoneSupport: 'Phone support',
  prioritySupport: 'Priority support',
  prioritySupport24x7: 'Priority support 24x7',
  reportsAnalytics: 'Reports analytics',
  classScheduling: 'Class scheduling',
  mobileAppAccess: 'Mobile app access',
  customBranding: 'Custom branding',
  realTimeNotifications: 'Real-time notifications',
  paymentRecording: 'Payment recording',
};
