import { OutstandingPayments, Skippers } from '@/types';

// Sample data
export const initialData: OutstandingPayments[] = [
  {
    id: '1',
    gymNo: '#00001',
    name: 'Arnold Schwarzneger',
    avatar: '/placeholder.svg?height=32&width=32',
    package: 'Monthly',
    feeStatus: 'partially_paid',
    amount: '2000',
  },
  {
    id: '2',
    gymNo: '#00002',
    name: 'Amit Choudhury',
    avatar: '/placeholder.svg?height=32&width=32',
    package: 'Yearly',
    feeStatus: 'paid',
    amount: '2000',
  },
  {
    id: '3',
    gymNo: '#00003',
    name: 'Sneha Reddy',
    avatar: '/placeholder.svg?height=32&width=32',
    package: 'Quarterly',
    feeStatus: 'partially_paid',
    amount: '2000',
  },
  {
    id: '4',
    gymNo: '#00004',
    name: 'Arjun Mehta',
    avatar: '/placeholder.svg?height=32&width=32',
    package: 'Monthly',
    feeStatus: 'paid',
    amount: '2000',
  },
  {
    id: '5',
    gymNo: '#00005',
    name: 'Karan Verma',
    avatar: '/placeholder.svg?height=32&width=32',
    package: 'Yearly',
    feeStatus: 'unpaid',
    amount: '2000',
  },
  {
    id: '6',
    gymNo: '#00006',
    name: 'Priya Sharma',
    avatar: '/placeholder.svg?height=32&width=32',
    package: 'Half_Yearly',
    feeStatus: 'paid',
    amount: '2000',
  },
  {
    id: '7',
    gymNo: '#00007',
    name: 'John Doe',
    avatar: '/placeholder.svg?height=32&width=32',
    package: 'Monthly',
    feeStatus: 'unpaid',
    amount: '2000',
  },
  {
    id: '8',
    gymNo: '#00008',
    name: 'Sophia Williams',
    avatar: '/placeholder.svg?height=32&width=32',
    package: 'Yearly',
    feeStatus: 'partially_paid',
    amount: '2000',
  },
  {
    id: '9',
    gymNo: '#00009',
    name: 'Ankit Yadav',
    avatar: '/placeholder.svg?height=32&width=32',
    package: 'Quarterly',
    feeStatus: 'paid',
    amount: '2000',
  },
  {
    id: '10',
    gymNo: '#00010',
    name: 'Emma Taylor',
    avatar: '/placeholder.svg?height=32&width=32',
    package: 'Half_Yearly',
    feeStatus: 'unpaid',
    amount: '2000',
  },
  {
    id: '11',
    gymNo: '#00011',
    name: 'David Johnson',
    avatar: '/placeholder.svg?height=32&width=32',
    package: 'Monthly',
    feeStatus: 'paid',
    amount: '2000',
  },
  {
    id: '12',
    gymNo: '#00012',
    name: 'Olivia Brown',
    avatar: '/placeholder.svg?height=32&width=32',
    package: 'Yearly',
    feeStatus: 'partially_paid',
    amount: '2000',
  },
  {
    id: '13',
    gymNo: '#00013',
    name: 'Nikhil Sharma',
    avatar: '/placeholder.svg?height=32&width=32',
    package: 'Special',
    feeStatus: 'paid',
    amount: '2000',
  },
  {
    id: '14',
    gymNo: '#00014',
    name: 'Isabella Garcia',
    avatar: '/placeholder.svg?height=32&width=32',
    package: 'Half_Yearly',
    feeStatus: 'unpaid',
    amount: '2000',
  },
  {
    id: '15',
    gymNo: '#00015',
    name: 'Ethan Anderson',
    avatar: '/placeholder.svg?height=32&width=32',
    package: 'Quarterly',
    feeStatus: 'unpaid',
    amount: '2000',
  },
  {
    id: '16',
    gymNo: '#00016',
    name: 'Mia Martinez',
    avatar: '/placeholder.svg?height=32&width=32',
    package: 'Monthly',
    feeStatus: 'paid',
    amount: '2000',
  },
  {
    id: '17',
    gymNo: '#00017',
    name: 'Liam Wilson',
    avatar: '/placeholder.svg?height=32&width=32',
    package: 'Yearly',
    feeStatus: 'partially_paid',
    amount: '2000',
  },
  {
    id: '18',
    gymNo: '#00018',
    name: 'Ella Rodriguez',
    avatar: '/placeholder.svg?height=32&width=32',
    package: 'Special',
    feeStatus: 'paid',
    amount: '2000',
  },
  {
    id: '19',
    gymNo: '#00019',
    name: 'Noah Clark',
    avatar: '/placeholder.svg?height=32&width=32',
    package: 'Quarterly',
    feeStatus: 'unpaid',
    amount: '2000',
  },
  {
    id: '20',
    gymNo: '#00020',
    name: 'Sophia Lewis',
    avatar: '/placeholder.svg?height=32&width=32',
    package: 'Half_Yearly',
    feeStatus: 'partially_paid',
    amount: '2000',
  },
];

export const skipperData: Skippers[] = [
  {
    id: '1',
    gymNo: '#00001',
    name: 'Arnold Schwarzneger',
    avatar: '/placeholder.svg?height=32&width=32',
    lastCheckIn: '02/24/2024',
    sinceLastCheckIn: '04',
  },
  {
    id: '2',
    gymNo: '#00002',
    name: 'Amit Choudhury',
    avatar: '/placeholder.svg?height=32&width=32',
    lastCheckIn: '02/24/2024',
    sinceLastCheckIn: '04',
  },
  {
    id: '3',
    gymNo: '#00003',
    name: 'Sneha Reddy',
    avatar: '/placeholder.svg?height=32&width=32',
    lastCheckIn: 'Quarterly',
    sinceLastCheckIn: '04',
  },
  {
    id: '4',
    gymNo: '#00004',
    name: 'Arjun Mehta',
    avatar: '/placeholder.svg?height=32&width=32',
    lastCheckIn: '02/24/2024',
    sinceLastCheckIn: '04',
  },
  {
    id: '5',
    gymNo: '#00005',
    name: 'Karan Verma',
    avatar: '/placeholder.svg?height=32&width=32',
    lastCheckIn: '02/24/2024',
    sinceLastCheckIn: '04',
  },
  {
    id: '6',
    gymNo: '#00006',
    name: 'Priya Sharma',
    avatar: '/placeholder.svg?height=32&width=32',
    lastCheckIn: 'Half_02/24/2024',
    sinceLastCheckIn: '04',
  },
  {
    id: '7',
    gymNo: '#00007',
    name: 'John Doe',
    avatar: '/placeholder.svg?height=32&width=32',
    lastCheckIn: '02/24/2024',
    sinceLastCheckIn: '04',
  },
  {
    id: '8',
    gymNo: '#00008',
    name: 'Sophia Williams',
    avatar: '/placeholder.svg?height=32&width=32',
    lastCheckIn: '02/24/2024',
    sinceLastCheckIn: '04',
  },
  {
    id: '9',
    gymNo: '#00009',
    name: 'Ankit Yadav',
    avatar: '/placeholder.svg?height=32&width=32',
    lastCheckIn: 'Quarterly',
    sinceLastCheckIn: '04',
  },
  {
    id: '10',
    gymNo: '#00010',
    name: 'Emma Taylor',
    avatar: '/placeholder.svg?height=32&width=32',
    lastCheckIn: 'Half_02/24/2024',
    sinceLastCheckIn: '04',
  },
  {
    id: '11',
    gymNo: '#00011',
    name: 'David Johnson',
    avatar: '/placeholder.svg?height=32&width=32',
    lastCheckIn: '02/24/2024',
    sinceLastCheckIn: '04',
  },
  {
    id: '12',
    gymNo: '#00012',
    name: 'Olivia Brown',
    avatar: '/placeholder.svg?height=32&width=32',
    lastCheckIn: '02/24/2024',
    sinceLastCheckIn: '04',
  },
  {
    id: '13',
    gymNo: '#00013',
    name: 'Nikhil Sharma',
    avatar: '/placeholder.svg?height=32&width=32',
    lastCheckIn: 'Special',
    sinceLastCheckIn: '04',
  },
  {
    id: '14',
    gymNo: '#00014',
    name: 'Isabella Garcia',
    avatar: '/placeholder.svg?height=32&width=32',
    lastCheckIn: 'Half_02/24/2024',
    sinceLastCheckIn: '04',
  },
  {
    id: '15',
    gymNo: '#00015',
    name: 'Ethan Anderson',
    avatar: '/placeholder.svg?height=32&width=32',
    lastCheckIn: 'Quarterly',
    sinceLastCheckIn: '04',
  },
  {
    id: '16',
    gymNo: '#00016',
    name: 'Mia Martinez',
    avatar: '/placeholder.svg?height=32&width=32',
    lastCheckIn: '02/24/2024',
    sinceLastCheckIn: '04',
  },
  {
    id: '17',
    gymNo: '#00017',
    name: 'Liam Wilson',
    avatar: '/placeholder.svg?height=32&width=32',
    lastCheckIn: '02/24/2024',
    sinceLastCheckIn: '04',
  },
  {
    id: '18',
    gymNo: '#00018',
    name: 'Ella Rodriguez',
    avatar: '/placeholder.svg?height=32&width=32',
    lastCheckIn: '02/24/2024',
    sinceLastCheckIn: '04',
  },
  {
    id: '19',
    gymNo: '#00019',
    name: 'Noah Clark',
    avatar: '/placeholder.svg?height=32&width=32',
    lastCheckIn: '02/24/2024',
    sinceLastCheckIn: '04',
  },
  {
    id: '20',
    gymNo: '#00020',
    name: 'Sophia Lewis',
    avatar: '/placeholder.svg?height=32&width=32',
    lastCheckIn: '02/24/2024',
    sinceLastCheckIn: '04',
  },
];
